dataset:
  name: "CIFAR-10"
  num_classes: 10
  image_size: 32
  mean: [0.4914, 0.4822, 0.4465]
  std:  [0.2023, 0.1994, 0.2010]

training:
  batch_size: 128
  epochs: 15
  learning_rate: 0.0001     # Much smaller LR for fine-tuning
  num_workers: 2
  seed: 42

augmentation:
  use_augmentation: true

paths:
  data_dir: "data"
  checkpoint_dir: "checkpoints"
